# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb5a7b480ff3b6617e67690967f1ac29"
name = "Abandoned Cart Recovery"
handle = "abandoned-cart-recovery-4"
application_url = "https://ryan-comprehensive-ye-paid.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "candystoredev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ryan-comprehensive-ye-paid.trycloudflare.com/auth/callback",
  "https://ryan-comprehensive-ye-paid.trycloudflare.com/auth/shopify/callback",
  "https://ryan-comprehensive-ye-paid.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
